# AVAAD AI Cost Tracking Configuration
# Configuration for tracking AI agent usage costs

models:
  claude-sonnet-4:
    input_cost: 0.003
    output_cost: 0.015
    provider: anthropic
    currency: USD
  
  claude-opus-4:
    input_cost: 0.015
    output_cost: 0.075
    provider: anthropic
    currency: USD
  
  gpt-4o:
    input_cost: 0.005
    output_cost: 0.015
    provider: openai
    currency: USD
  
  gpt-4o-mini:
    input_cost: 0.00015
    output_cost: 0.0006
    provider: openai
    currency: USD
  
  gpt-4-turbo:
    input_cost: 0.01
    output_cost: 0.03
    provider: openai
    currency: USD

budgets:
  daily: 50.0
  weekly: 200.0
  monthly: 800.0
  project_total: 5000.0

alerts:
  daily_warning: 40.0
  daily_critical: 45.0
  weekly_warning: 160.0
  weekly_critical: 190.0
  monthly_warning: 700.0
  monthly_critical: 750.0

reporting:
  # Default report period (in days)
  default_period: 7
  
  # Include detailed breakdowns
  show_agent_breakdown: true
  show_model_breakdown: true
  show_story_breakdown: true
  
  # Cost efficiency thresholds
  efficiency:
    cost_per_task_warning: 5.0
    cost_per_task_critical: 10.0

currency: USD

# Cost estimation for common tasks
estimates:
  code_review:
    tokens: 2000
    estimated_cost: 0.15
  
  bug_fix:
    tokens: 3000
    estimated_cost: 0.25
  
  feature_implementation:
    tokens: 5000
    estimated_cost: 0.50
  
  documentation:
    tokens: 1500
    estimated_cost: 0.10

# Logging settings
logging:
  level: INFO
  file: logs/ai_costs.jsonl
  retention_days: 90

# ROI calculation settings
roi:
  developer_hourly_rate: 50.0
  efficiency_multiplier: 3.0  # AI is 3x faster than human
  
  # Estimated time savings per task type
  time_savings:
    code_review: 0.5
    bug_fix: 2.0
    feature_implementation: 4.0
    documentation: 1.0